<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="pt-BR">

<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
</head>

<body>
    <table id="maintable" cellspacing="0" cellpadding="0" align="center" border="0" width="600">
        <tbody style="font-family: Arial, sans-serif; color: #4f5052; font-size: 16px">
            <tr>
                <td style="text-align: center;">
                    <img src="http://www.thunderbold.com.br/minimal-creative/images/header_gradient.png" alt="Header">
                </td>
            </tr>
            <tr>
                <td colspan="2" style="color: #3A3A3A; font-size: 16px; text-align: justify;
                border-style: solid; 
                padding: 10px 20px;
                border-left-width:5px;
                border-right-width:5px;
                -moz-border-image: -moz-linear-gradient(3deg, #2679ff 0%, #a837f9 100%) 1 100%;
                -webkit-border-image: -webkit-gradient(3deg, #2679ff 0%, #a837f9 100%), color-stop(33.33333%, #000000), color-stop(66.66667%, #000000), color-stop(100%, rgba(0, 0, 0, 0)) 1 100%;
                -webkit-border-image: -webkit-linear-gradient(3deg, #2679ff 0%, #a837f9 100%) 1 100%;
                -o-border-image: -o-linear-gradient(3deg, #2679ff 0%, #a837f9 100%) 1 100%;
                border-image: linear-gradient(3deg, #2679ff 0%, #a837f9 100%) 1 100%;">
                    <br>
                        <strong>Novo Detalhe de Projeto</strong>
                    </br>
                    <br>    
                        <b>Nome:</b> {NAME}
                    </br>
                    <br>    
                        <b>Email:</b> {EMAIL}
                    </br>
                    <br>    
                        <b>O seu projeto é uma ideia pessoal em fase inicial ou é um projeto para uma empresa com escopo planejado? </b> {PROJECT_TYPE}
                    </br>
                    <br>    
                        <b>Você já tem o design de telas? </b> {USER_HAS_SCREEN_DESIGN}
                    </br>
                    <br>    
                        <b>Já possui site pessoal ou corporativo? </b> {USER_HAS_SITE}
                    </br>
                    <br>    
                        <b>Você já tem algo desenvolvido? </b> {PROJECT_STAGE}
                    </br>
                    <br>    
                        <b>O que será desenvolvido?</b>  {PROJECT_DEFINITION}
                    </br>
                    <br>
                </td>
            </tr>
            <tr>
                <td style="text-align: center;">
                    <img src="http://www.thunderbold.com.br/minimal-creative/images/footer_gradient.png" alt="Footer">
                </td>
            </tr>
        </tbody>
    </table>
</body>

</html>